import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy Policy — Queritae" };

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12 text-[var(--color-text-secondary)]">
      <div className="mb-6 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-3 text-2xs uppercase tracking-wide text-[var(--color-text-tertiary)]">
        Draft — review before relying on this. Not legal advice.
      </div>
      <h1 className="mb-4 font-display text-2xl text-[var(--color-text-primary)]">
        Privacy Policy
      </h1>
      <p className="mb-8">Last updated: 2026-06-23.</p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        What we collect
      </h2>
      <p className="mb-4">
        When you sign in via GitHub OAuth, we receive and store your GitHub user ID, username,
        display name, and public email address. We use this to identify your account and link you to
        your connected content repository.
      </p>
      <p className="mb-6">
        We also collect usage and conversation data: questions you submit to your AI persona,
        AI-generated answers, citation references, and metadata such as timestamps and answer counts.
        This data is stored per-account and is used to operate the Service (answer delivery, quota
        tracking, conversation history). We do not sell this data or use it to train AI models.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        How we use it
      </h2>
      <p className="mb-6">
        We process your personal data to provide and improve the Service: authenticating your
        session, routing your questions to the AI backend, enforcing plan limits, sending
        transactional emails (billing receipts, plan change confirmations), and displaying your
        profile and CV. We may also use aggregated, anonymised analytics to understand how the
        Service is used and where to improve it. We do not use your data for advertising or share
        it with data brokers.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        Third parties
      </h2>
      <p className="mb-4">
        <strong className="text-[var(--color-text-primary)]">GitHub</strong> — you authenticate
        via GitHub OAuth. GitHub&apos;s privacy policy governs data processed on their platform.
        We receive only the profile data your GitHub account makes available to OAuth apps.
      </p>
      <p className="mb-4">
        <strong className="text-[var(--color-text-primary)]">Stripe</strong> — paid plans are
        billed through Stripe. Stripe processes your payment information directly; we do not store
        full card numbers. Stripe&apos;s privacy policy applies to payment data.
      </p>
      <p className="mb-4">
        <strong className="text-[var(--color-text-primary)]">Anthropic</strong> — AI answers are
        generated by Anthropic&apos;s Claude models. Your questions and relevant context from your
        content repository are sent to Anthropic&apos;s API to produce answers. Anthropic&apos;s
        API usage policies and privacy terms apply to that processing.
      </p>
      <p className="mb-6">
        <strong className="text-[var(--color-text-primary)]">Vercel &amp; Neon</strong> — the
        Service is hosted on Vercel and our database runs on Neon (Postgres). Both are
        infrastructure providers that process data to operate the Service; they do not access your
        data for their own commercial purposes.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        Cookies &amp; session
      </h2>
      <p className="mb-6">
        We use a session cookie to keep you signed in between page loads. This cookie is
        first-party, httpOnly, and strictly necessary to operate the Service. We do not use
        tracking or advertising cookies. You can clear your session by signing out or clearing
        your browser cookies, which will end your authenticated session.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        Data retention &amp; deletion
      </h2>
      <p className="mb-6">
        We retain your account data and conversation history for as long as your account is active.
        If you delete your account, we will remove your personal data from our systems within a
        reasonable period, except where we are required to retain it for legal or accounting
        purposes. To request account deletion, contact us at the address below.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        Your rights (EU / GDPR)
      </h2>
      <p className="mb-6">
        If you are located in the European Economic Area or the United Kingdom, you have rights
        under the General Data Protection Regulation (GDPR) or UK GDPR, including the right to
        access, correct, or delete your personal data, to restrict or object to processing, and to
        data portability. You also have the right to lodge a complaint with your local supervisory
        authority. To exercise any of these rights, contact us at the address below and we will
        respond within the timeframe required by applicable law.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">Contact</h2>
      <p className="mb-6">
        Privacy questions, data requests, or concerns about this policy should be sent to{" "}
        <a
          href="mailto:abuse@queritae.com"
          className="text-[var(--color-primary)] underline-offset-2 hover:underline"
        >
          abuse@queritae.com
        </a>
        .
      </p>
    </main>
  );
}
