import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service — Queritae" };

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12 text-[var(--color-text-secondary)]">
      <div className="mb-6 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-3 text-2xs uppercase tracking-wide text-[var(--color-text-tertiary)]">
        Draft — review before relying on this. Not legal advice.
      </div>
      <h1 className="mb-4 font-display text-2xl text-[var(--color-text-primary)]">
        Terms of Service
      </h1>
      <p className="mb-8">Last updated: 2026-06-23.</p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">Acceptance</h2>
      <p className="mb-6">
        By creating an account or using Queritae (the &quot;Service&quot;), you agree to be bound
        by these Terms of Service. If you do not agree, do not use the Service. These terms form a
        binding agreement between you and the operator of queritae.com.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">The Service</h2>
      <p className="mb-6">
        Queritae is a Software-as-a-Service platform that transforms a GitHub-hosted content
        repository into a conversational AI persona — a cited, chat-based interface backed by your
        own writing, together with a printable CV renderer. Answers are generated by Anthropic&apos;s
        Claude models on your behalf. The Service is provided &quot;as is&quot; and features may
        change over time.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        Accounts &amp; eligibility
      </h2>
      <p className="mb-6">
        You must be at least 16 years old to use the Service. You sign in via GitHub OAuth; you are
        responsible for the security of your GitHub credentials and for all activity that occurs
        under your account. You must provide accurate information and keep it current. We reserve
        the right to suspend or terminate accounts that violate these terms.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        Acceptable use
      </h2>
      <p className="mb-6">
        You may use the Service only for lawful purposes and in accordance with these terms. You
        must not upload or link content that is illegal, harmful, defamatory, or that infringes the
        intellectual-property rights of others. You must not attempt to reverse-engineer, overload,
        or circumvent any technical measures of the Service. Automated access (bots, scrapers) is
        not permitted without prior written consent.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        Content &amp; ownership
      </h2>
      <p className="mb-6">
        You retain all intellectual-property rights in the content you provide through your linked
        GitHub repository. By connecting that repository you grant us a limited, non-exclusive
        licence to process and display the content solely to operate the Service on your behalf.
        We do not claim ownership of your content and will not use it to train AI models without
        your explicit consent. You are solely responsible for ensuring you have the right to publish
        that content.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        Fees &amp; billing
      </h2>
      <p className="mb-6">
        The Service is available on a Free plan (limited to a set number of answers per month) and
        a Pro plan (currently $9 per month), billed through Stripe. Fees are charged in advance for
        each billing period. We may change pricing at any time with reasonable notice; continued use
        after a price change constitutes acceptance of the new pricing. Refunds are handled on a
        case-by-case basis — contact us at the address below.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">Disclaimers</h2>
      <p className="mb-6">
        The Service is provided on an &quot;as is&quot; and &quot;as available&quot; basis without
        warranties of any kind, express or implied. AI-generated answers may be inaccurate,
        incomplete, or outdated; they should not be treated as professional advice. We do not
        warrant that the Service will be uninterrupted, error-free, or free of harmful components.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        Limitation of liability
      </h2>
      <p className="mb-6">
        To the fullest extent permitted by applicable law, we shall not be liable for any indirect,
        incidental, special, consequential, or punitive damages, or any loss of profits, data, or
        goodwill, arising out of or in connection with your use of — or inability to use — the
        Service. Our total aggregate liability to you for any claim shall not exceed the fees you
        paid to us in the twelve months preceding the claim.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">
        Changes to these terms
      </h2>
      <p className="mb-6">
        We may update these terms from time to time. When we do, we will revise the &quot;Last
        updated&quot; date above and, for material changes, notify you by email or via an in-app
        prompt. Your continued use of the Service after changes take effect constitutes your
        acceptance of the revised terms.
      </p>

      <h2 className="mb-2 font-display text-lg text-[var(--color-text-primary)]">Contact</h2>
      <p className="mb-6">
        Questions about these terms should be sent to{" "}
        <a
          href="mailto:abuse@queritae.com"
          className="text-[var(--color-primary)] underline-offset-2 hover:underline"
        >
          abuse@queritae.com
        </a>
        . We aim to respond within a reasonable timeframe.
      </p>
    </main>
  );
}
