export type UiLang = "en" | "fr";

export const UI_STRINGS = {
  en: {
    headline: "Alexandre Collet — queryable CV",
    intro:
      "Hi — I'm an agent that can answer questions about Alexandre's background, experience, and projects. Ask me anything.",
    placeholder: "Ask a question…",
    send: "Send",
    startersTitle: "Try one of these",
    starters: [
      "What's his most recent role?",
      "What's his experience with AI?",
      "How do I contact him?",
    ],
    agentLabel: "agent",
    statusThinking: "thinking",
    statusReady: "ready",
    forwardAction: "Send this question to Alexandre",
    forward: {
      prompt: "Want a reply? Leave a contact (optional).",
      placeholder: "Email or LinkedIn URL",
      send: "Send to Alexandre",
      cancel: "Cancel",
      successWithContact: "Sent. Alexandre will reply at the contact you left.",
      successNoContact: "Sent. Alexandre will see it next time he checks.",
      errorRetry: "Couldn't send — try again.",
    },
    genericError: "Something went wrong — please try again.",
    identity: {
      chipPrefix: "Recognized you as",
      hiring: "hiring",
    },
    footer: {
      transparency: "Everything this agent knows is in the public repo.",
      systemPrompt: "View the system prompt",
      kb: "View the knowledge base",
      repo: "GitHub repo",
      mcpDocs: "Connect from your agent (MCP docs)",
    },
    mcp: {
      buttonLabel: "Connect via MCP",
      title: "Connect via MCP",
      intro:
        "This CV agent is also available over the Model Context Protocol. Point any MCP client at the endpoint below using the Streamable-HTTP transport.",
      endpointLabel: "Endpoint",
      configLabel: "Client configuration",
      configNote:
        "For Claude Desktop, add this to claude_desktop_config.json. Other JSON-config clients (Cursor and similar) use the same mcpServers block.",
      toolsTitle: "Tools",
      tools: [
        {
          name: "ask",
          desc: "Ask a question about Alexandre. Returns an answer and a conversationId to reuse on follow-ups.",
        },
        {
          name: "forward_question",
          desc: "Leave a question for Alexandre to answer later.",
        },
      ],
      copy: "Copy",
      copied: "Copied",
      close: "Close",
    },
    themeToggle: "Switch between light and dark theme",
    about: {
      buttonLabel: "About this project",
      title: "About this project",
      close: "Close",
      printableCv: "Printable CV",
    },
    kbPanel: {
      show: "Show the knowledge base panel",
      hide: "Hide the knowledge base panel",
    },
    kb: {
      title: "knowledge base",
      unavailable: "The knowledge base is unavailable.",
      referenced: "Referenced in this conversation",
      allDocuments: "All documents",
      notInKb: "That document isn't in the knowledge base.",
      back: "files",
      loading: "Loading…",
      loadError: "Couldn't load this file.",
      github: "GitHub",
      expand: "expand",
      minimize: "minimize",
      close: "close",
      details: "File details",
      showDetails: "Show file details",
      hideDetails: "Hide file details",
      backToList: "Back to the file list",
      expandFocus: "Expand to focus mode",
      exitFocus: "Exit focus mode",
      showPanel: "Show the knowledge base panel",
      closePanel: "Close the knowledge base panel",
      resizePanel: "Resize the knowledge base panel",
      panelLabel: "Knowledge base",
      meta: {
        company: "Company",
        role: "Role",
        period: "Period",
        location: "Location",
        year: "Year",
        link: "Link",
        stack: "Stack",
        tags: "Tags",
      },
    },
  },
  fr: {
    headline: "Alexandre Collet — CV interrogeable",
    intro:
      "Bonjour — je suis un agent qui peut répondre à des questions sur le parcours, l'expérience et les projets d'Alexandre. Posez-moi vos questions.",
    placeholder: "Posez une question…",
    send: "Envoyer",
    startersTitle: "Essayez l'une de ces questions",
    starters: [
      "Quel est son poste le plus récent ?",
      "Quelle est son expérience en IA ?",
      "Comment le contacter ?",
    ],
    agentLabel: "agent",
    statusThinking: "réflexion",
    statusReady: "prêt",
    forwardAction: "Envoyer cette question à Alexandre",
    forward: {
      prompt: "Souhaitez-vous une réponse ? Laissez un contact (facultatif).",
      placeholder: "E-mail ou URL LinkedIn",
      send: "Envoyer à Alexandre",
      cancel: "Annuler",
      successWithContact: "Envoyé. Alexandre vous répondra au contact laissé.",
      successNoContact: "Envoyé. Alexandre le verra lors de son prochain passage.",
      errorRetry: "Échec de l'envoi — réessayez.",
    },
    genericError: "Une erreur s'est produite — réessayez.",
    identity: {
      chipPrefix: "Vous avez été reconnu·e comme",
      hiring: "recrute pour",
    },
    footer: {
      transparency: "Tout ce que cet agent sait est dans le dépôt public.",
      systemPrompt: "Voir le prompt système",
      kb: "Voir la base de connaissances",
      repo: "Dépôt GitHub",
      mcpDocs: "Se connecter depuis votre agent (docs MCP)",
    },
    mcp: {
      buttonLabel: "Se connecter via MCP",
      title: "Se connecter via MCP",
      intro:
        "Cet agent CV est aussi accessible via le Model Context Protocol. Connectez n'importe quel client MCP au point d'accès ci-dessous avec le transport Streamable-HTTP.",
      endpointLabel: "Point d'accès",
      configLabel: "Configuration du client",
      configNote:
        "Pour Claude Desktop, ajoutez ceci à claude_desktop_config.json. Les autres clients à configuration JSON (Cursor et similaires) utilisent le même bloc mcpServers.",
      toolsTitle: "Outils",
      tools: [
        {
          name: "ask",
          desc: "Poser une question sur Alexandre. Renvoie une réponse et un conversationId à réutiliser pour les questions suivantes.",
        },
        {
          name: "forward_question",
          desc: "Laisser une question à laquelle Alexandre répondra plus tard.",
        },
      ],
      copy: "Copier",
      copied: "Copié",
      close: "Fermer",
    },
    themeToggle: "Basculer entre thème clair et sombre",
    about: {
      buttonLabel: "À propos de ce projet",
      title: "À propos de ce projet",
      close: "Fermer",
      printableCv: "CV imprimable",
    },
    kbPanel: {
      show: "Afficher la base de connaissances",
      hide: "Masquer la base de connaissances",
    },
    kb: {
      title: "base de connaissances",
      unavailable: "La base de connaissances est indisponible.",
      referenced: "Référencé dans cette conversation",
      allDocuments: "Tous les documents",
      notInKb: "Ce document n'est pas dans la base de connaissances.",
      back: "fichiers",
      loading: "Chargement…",
      loadError: "Impossible de charger ce fichier.",
      github: "GitHub",
      expand: "agrandir",
      minimize: "réduire",
      close: "fermer",
      details: "Détails du fichier",
      showDetails: "Afficher les détails du fichier",
      hideDetails: "Masquer les détails du fichier",
      backToList: "Retour à la liste des fichiers",
      expandFocus: "Passer en mode focus",
      exitFocus: "Quitter le mode focus",
      showPanel: "Afficher la base de connaissances",
      closePanel: "Fermer la base de connaissances",
      resizePanel: "Redimensionner la base de connaissances",
      panelLabel: "Base de connaissances",
      meta: {
        company: "Entreprise",
        role: "Rôle",
        period: "Période",
        location: "Lieu",
        year: "Année",
        link: "Lien",
        stack: "Stack",
        tags: "Tags",
      },
    },
  },
} as const;

/** The full string table for one locale (a union over the locales). */
export type UiStrings = (typeof UI_STRINGS)[UiLang];

/** The knowledge-base subset, surfaced to KB components via KbContext. */
export type KbStrings = (typeof UI_STRINGS)[UiLang]["kb"];
