import type { Persona } from "@/lib/persona";

export type UiLang = "en" | "fr";

export function buildUiStrings(persona: Persona) {
  const en = persona.i18n.en;
  const fr = persona.i18n.fr;
  const enGiven = persona.givenName;
  const frGiven = persona.givenName;
  const frGivenApos = fr.givenWithApostrophe ?? `de ${frGiven}`;

  return {
    en: {
      headline: `${persona.fullName} — queryable CV`,
      intro: `Hi — I'm an agent that can answer questions about ${enGiven}'s background, experience, and projects. Ask me anything.`,
      placeholder: "Ask a question…",
      send: "Send",
      startersTitle: "Try one of these",
      starters: [
        `What's ${en.possessive} most recent role?`,
        `What's ${en.possessive} experience with AI?`,
        `How do I contact ${en.objectPronoun}?`,
      ],
      agentLabel: "agent",
      statusThinking: "thinking",
      statusReady: "ready",
      clearChat: {
        action: "Clear chat",
        confirm: "Confirm?",
        cancel: "Cancel",
      },
      thinking: {
        generic: "Thinking…",
      },
      forwardAction: `Send this question to ${enGiven}`,
      forward: {
        prompt: "Want a reply? Leave a contact (optional).",
        placeholder: "Email or LinkedIn URL",
        send: `Send to ${enGiven}`,
        cancel: "Cancel",
        successWithContact: `Sent. ${enGiven} will reply at the contact you left.`,
        successNoContact: `Sent. ${enGiven} will see it next time ${en.subjectPronoun} checks.`,
        errorRetry: "Couldn't send — try again.",
      },
      genericError: "Something went wrong — please try again.",
      planLimit: {
        notice: `${enGiven} has answered this month's included questions. Leave yours below — you'll get a personal reply.`,
        questionPlaceholder: "Your question…",
        contactPlaceholder: "Email or LinkedIn (optional)",
        submit: `Send to ${enGiven}`,
      },
      identity: {
        chipPrefix: "Recognized you as",
        hiring: "hiring",
      },
      footer: {
        transparency: "Everything this agent knows is in the public repo.",
        systemPrompt: "View the system prompt",
        kb: "View the knowledge base",
        repo: "GitHub repo",
        mcpDocs: "Connect from your agent (MCP docs)",
      },
      mcp: {
        buttonLabel: "Connect via MCP",
        title: "Connect via MCP",
        intro:
          "This CV agent is also available over the Model Context Protocol. Point any MCP client at the endpoint below using the Streamable-HTTP transport.",
        endpointLabel: "Endpoint",
        configLabel: "Client configuration",
        configNote:
          "For Claude Desktop, add this to claude_desktop_config.json. Other JSON-config clients (Cursor and similar) use the same mcpServers block.",
        toolsTitle: "Tools",
        tools: [
          {
            name: "ask",
            desc: `Ask a question about ${enGiven}. Returns an answer and a conversationId to reuse on follow-ups.`,
          },
          {
            name: "forward_question",
            desc: `Leave a question for ${enGiven} to answer later.`,
          },
        ],
        copy: "Copy",
        copied: "Copied",
        close: "Close",
      },
      themeToggle: "Switch between light and dark theme",
      sourceRepoLabel: "View CV source on GitHub",
      about: {
        buttonLabel: "About this project",
        title: "About this project",
        close: "Close",
        printableCv: "Printable CV",
        report: "Report this persona",
      },
      kbPanel: {
        show: "Show the knowledge base panel",
        hide: "Hide the knowledge base panel",
      },
      kb: {
        title: "knowledge base",
        unavailable: "The knowledge base is unavailable.",
        referenced: "Referenced in this conversation",
        allDocuments: "All documents",
        notInKb: "That document isn't in the knowledge base.",
        back: "files",
        loading: "Loading…",
        loadError: "Couldn't load this file.",
        github: "GitHub",
        expand: "expand",
        minimize: "minimize",
        close: "close",
        details: "File details",
        showDetails: "Show file details",
        hideDetails: "Hide file details",
        backToList: "Back to the file list",
        expandFocus: "Expand to focus mode",
        exitFocus: "Exit focus mode",
        showPanel: "Show the knowledge base panel",
        closePanel: "Close the knowledge base panel",
        resizePanel: "Resize the knowledge base panel",
        panelLabel: "Knowledge base",
        copy: "Copy",
        copied: "Copied",
        copyAria: "Copy document content",
        download: "Download",
        downloadAria: "Download document",
        print: "Print",
        printAria: "Print or save as PDF",
        share: "Share",
        shareAria: "Share a link to this CV",
        cv: "Curriculum Vitae",
        openCv: "Open CV",
        filterPlaceholder: "Filter…",
        clearFilter: "Clear filter",
        noMatches: "No documents match.",
        referencedLens: "Referenced",
        referencedLensAria: "Show only documents referenced in this conversation",
        sourcesTitle: "Sources · this answer",
        sourcesCollapse: "Collapse sources",
        sourcesExpand: "Expand sources",
        densityLabel: "Row spacing",
        densityCompact: "Compact",
        densityComfortable: "Comfortable",
        peekLoading: "Loading preview…",
        outline: "Outline",
        outlineAria: "Jump to a section",
        /** Chip-button label template — `{n}` is the citation number. */
        citationJump: "Show citation {n} in chat",
        sections: {
          experience: "Experience",
          projects: "Projects",
          talks: "Talks",
          recommendations: "Recommendations",
          other: "Other",
        },
        expandGroup: "Expand",
        collapseGroup: "Collapse",
        meta: {
          company: "Company",
          role: "Role",
          period: "Period",
          location: "Location",
          year: "Year",
          link: "Link",
          stack: "Stack",
          tags: "Tags",
        },
      },
    },
    fr: {
      headline: `${persona.fullName} — CV interrogeable`,
      intro: `Bonjour — je suis un agent qui peut répondre à des questions sur le parcours, l'expérience et les projets ${frGivenApos}. Posez-moi vos questions.`,
      placeholder: "Posez une question…",
      send: "Envoyer",
      startersTitle: "Essayez l'une de ces questions",
      starters: [
        `Quel est ${fr.possessive} poste le plus récent ?`,
        `Quelle est ${fr.possessive} expérience en IA ?`,
        `Comment ${fr.objectPronoun} contacter ?`,
      ],
      agentLabel: "agent",
      statusThinking: "réflexion",
      statusReady: "prêt",
      clearChat: {
        action: "Effacer",
        confirm: "Confirmer ?",
        cancel: "Annuler",
      },
      thinking: {
        generic: "Réflexion…",
      },
      forwardAction: `Envoyer cette question à ${frGiven}`,
      forward: {
        prompt: "Souhaitez-vous une réponse ? Laissez un contact (facultatif).",
        placeholder: "E-mail ou URL LinkedIn",
        send: `Envoyer à ${frGiven}`,
        cancel: "Annuler",
        successWithContact: `Envoyé. ${frGiven} vous répondra au contact laissé.`,
        successNoContact: `Envoyé. ${frGiven} ${fr.objectPronoun} verra lors de ${fr.possessive} prochain passage.`,
        errorRetry: "Échec de l'envoi — réessayez.",
      },
      genericError: "Une erreur s'est produite — réessayez.",
      planLimit: {
        notice: `${frGiven} a répondu aux questions incluses ce mois-ci. Laissez la vôtre ci-dessous — vous recevrez une réponse personnelle.`,
        questionPlaceholder: "Votre question…",
        contactPlaceholder: "Email ou LinkedIn (facultatif)",
        submit: `Envoyer à ${frGiven}`,
      },
      identity: {
        chipPrefix: "Vous avez été reconnu·e comme",
        hiring: "recrute pour",
      },
      footer: {
        transparency: "Tout ce que cet agent sait est dans le dépôt public.",
        systemPrompt: "Voir le prompt système",
        kb: "Voir la base de connaissances",
        repo: "Dépôt GitHub",
        mcpDocs: "Se connecter depuis votre agent (docs MCP)",
      },
      mcp: {
        buttonLabel: "Se connecter via MCP",
        title: "Se connecter via MCP",
        intro:
          "Cet agent CV est aussi accessible via le Model Context Protocol. Connectez n'importe quel client MCP au point d'accès ci-dessous avec le transport Streamable-HTTP.",
        endpointLabel: "Point d'accès",
        configLabel: "Configuration du client",
        configNote:
          "Pour Claude Desktop, ajoutez ceci à claude_desktop_config.json. Les autres clients à configuration JSON (Cursor et similaires) utilisent le même bloc mcpServers.",
        toolsTitle: "Outils",
        tools: [
          {
            name: "ask",
            desc: `Poser une question sur ${frGiven}. Renvoie une réponse et un conversationId à réutiliser pour les questions suivantes.`,
          },
          {
            name: "forward_question",
            desc: `Laisser une question à laquelle ${frGiven} répondra plus tard.`,
          },
        ],
        copy: "Copier",
        copied: "Copié",
        close: "Fermer",
      },
      themeToggle: "Basculer entre thème clair et sombre",
      sourceRepoLabel: "Voir la source du CV sur GitHub",
      about: {
        buttonLabel: "À propos de ce projet",
        title: "À propos de ce projet",
        close: "Fermer",
        printableCv: "CV imprimable",
        report: "Signaler ce profil",
      },
      kbPanel: {
        show: "Afficher la base de connaissances",
        hide: "Masquer la base de connaissances",
      },
      kb: {
        title: "base de connaissances",
        unavailable: "La base de connaissances est indisponible.",
        referenced: "Référencé dans cette conversation",
        allDocuments: "Tous les documents",
        notInKb: "Ce document n'est pas dans la base de connaissances.",
        back: "fichiers",
        loading: "Chargement…",
        loadError: "Impossible de charger ce fichier.",
        github: "GitHub",
        expand: "agrandir",
        minimize: "réduire",
        close: "fermer",
        details: "Détails du fichier",
        showDetails: "Afficher les détails du fichier",
        hideDetails: "Masquer les détails du fichier",
        backToList: "Retour à la liste des fichiers",
        expandFocus: "Passer en mode focus",
        exitFocus: "Quitter le mode focus",
        showPanel: "Afficher la base de connaissances",
        closePanel: "Fermer la base de connaissances",
        resizePanel: "Redimensionner la base de connaissances",
        panelLabel: "Base de connaissances",
        copy: "Copier",
        copied: "Copié",
        copyAria: "Copier le contenu du document",
        download: "Télécharger",
        downloadAria: "Télécharger le document",
        print: "Imprimer",
        printAria: "Imprimer ou enregistrer en PDF",
        share: "Partager",
        shareAria: "Partager un lien vers ce CV",
        cv: "Curriculum Vitae",
        openCv: "Ouvrir le CV",
        filterPlaceholder: "Filtrer…",
        clearFilter: "Effacer le filtre",
        noMatches: "Aucun document ne correspond.",
        referencedLens: "Référencés",
        referencedLensAria: "Afficher uniquement les documents référencés dans cette conversation",
        sourcesTitle: "Sources · cette réponse",
        sourcesCollapse: "Réduire les sources",
        sourcesExpand: "Afficher les sources",
        densityLabel: "Espacement des lignes",
        densityCompact: "Compact",
        densityComfortable: "Confortable",
        peekLoading: "Chargement de l’aperçu…",
        outline: "Plan",
        outlineAria: "Aller à une section",
        /** Gabarit du libellé des puces — `{n}` est le numéro de citation. */
        citationJump: "Afficher la citation {n} dans la conversation",
        sections: {
          experience: "Expérience",
          projects: "Projets",
          talks: "Conférences",
          recommendations: "Recommandations",
          other: "Autres",
        },
        expandGroup: "Déplier",
        collapseGroup: "Replier",
        meta: {
          company: "Entreprise",
          role: "Rôle",
          period: "Période",
          location: "Lieu",
          year: "Année",
          link: "Lien",
          stack: "Stack",
          tags: "Tags",
        },
      },
    },
  } as const;
}

export type UiStrings = ReturnType<typeof buildUiStrings>["en"];
export type KbStrings = UiStrings["kb"];
export type AllLocaleStrings = ReturnType<typeof buildUiStrings>;
